# MQTT options ---------------------------------------
mqtt_options:
  mqtt_ip: localhost
  mqtt_port: 1883

  topics: [
    {
      name: "receive_depth_image", 
      topic: "test/image/colour_image",
      is_subscribe: True,
      is_trigger: True
    },
    {
      name: "request_cloud_list",
      topic: "test/database/search/sku_data",
      is_subscribe: False,
      is_trigger: False
    },
    {
      name: "receive_cloud_list",
      topic: "test/database/search/matching_sku",
      is_subscribe: True,
      is_trigger: True
    }
  ]

image_options:
  region_of_interest: [0,0,2500,3000]
  trim_value: 0.0325

database_options:
  database_name: "test_database"
  database_table: "test_table"